data:
  class_path: datasets.ObjectDataModule
  init_args:
    data_dir: "/home/sapark/ped/dataset/Messytable_dataset"
    train_ratio: .5026
    #num_workers: 0
model:
  resolution: [325, 2, 450]  # Y,Z,X
  bounds: [0, 1800, 0, 1300, 0, 200]  # xmin,xmax,ymin,ymax,zmin,zmax
  #depth: [100, 0, 2000]
  num_cameras: 3
  num_ids: 121
  max_detections: 73
