data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "/home/sapark/MultiviewX"
model:
  resolution: [160, 2, 250]  # Y,Z,X
  bounds: [0, 1000, 0, 640, 0, 2]  # xmin,xmax,ymin,ymax,zmin,zmax
  depth: [100, 0, -20]
  num_cameras: 6
  num_ids: 350  # id: 0~349
  gating_threshold: 30000
